// globalvar.h
extern int RAM_COUNT;
extern int CPU_COUNT;
extern bool t0;
extern int INSTRUCTION_START ;
extern  int INSTRUCTION_END ;
extern int STACK_START ;
extern  int STACK_END ;
extern  int ARRAY_A_START ;
extern  int ARRAY_A_END ;
extern int ARRAY_B_START ;
extern  int ARRAY_B_END;
extern  int ARRAY_C_START ;
extern  int ARRAY_C_END ;
extern  int ARRAY_D_START ;
extern  int ARRAY_D_END ;
extern int clockCycle ;
extern int clockCycle2;
extern uint32_t ram[];
extern std::string output1[];
extern std::string output2[];